### ISSUE TITLE
Dynamic fees

### ISSUE THREAD

**Issue by eragmus** [arcbit/arcbit-ios#2]
Hi, various wallets (breadwallet, electrum, bitcoin core, ledger, mycelium, copay, bitgo) now have dynamic fees integrated by default. This is essential to help deal with future stress tests / spam attacks, one of which is impending (Coinwallet's plan to create a severe 30-day tx backlog in September).

What are Arcbit's thoughts? It may be prudent to prioritize this and have it out ASAP, given that September threat.

Thanks.

**Comment by stequald** [comment]
Dynamic fees is now in the latest version of Arcbit.
